project_id = "hehvnfeaekpaltkfkvxd"

[functions.chat-webhook]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.analyze-personality]
verify_jwt = true

[functions.fetch-bookmark-metadata]
verify_jwt = true

[functions.send-whatsapp-message]
verify_jwt = false
