// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hehvnfeaekpaltkfkvxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlaHZuZmVhZWtwYWx0a2ZrdnhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNTc3NTMsImV4cCI6MjA3NTgzMzc1M30.dUu-_wDv8n5r3ZgYnGyNJp4JjIY3FENdQxF2Zttnu2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});